Admin Site/Manage users in django admin/project/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import redirect

app_name = 'accounts'


class Login(LoginView):
    template_name = 'accounts/login.html'

    def get_success_url(self):
        return reverse_lazy('accounts:profile', args=[self.request.user.id])

    def form_invalid(self, form):
        response = super().form_invalid(form)
        messages.error(self.request, 'username or password are invalid. please try again.', extra_tags='validate_form')
        return redirect('accounts:login')


urlpatterns = [
    path('', Login.as_view(), name='login'),
    path('register/', views.register, name='register'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html', next_page=reverse_lazy('accounts:login')), name='logout'),
    path('profile/<int:id>/', views.profile, name='profile'),
    path('delete/<int:id>/', views.delete_user, name='delete_user'),
]

Admin Site/Manage users in django admin/project/library/urls.py
from django.urls import path
from . import views


#urlpatterns = [
#    path("", views.index, name="index"),
#]

Admin Site/Manage users in django admin/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]

Admin Site/Manage users in django admin/project/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager
from django.db.models.signals import post_save


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    date_joined = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    admin = models.BooleanField(default=False)
    staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def get_full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def get_short_name(self):
        return self.email

    def is_staff(self):
        return self.staff

    def is_admin(self):
        return self.admin

    def is_active(self):
        return self.active

    def has_perm(self, perm, obj=None):
        return True


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    overview = models.TextField(max_length=2000, blank=True)

    class Meta:
        default_permissions = ('add',)
        permissions = (('give_refund', 'Can refund customers'),
                       ('can_hire', 'Can hire employees'))


def create_profile(sender, **kwargs):
    if kwargs['created']:
        UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(receiver=create_profile, sender=User)

Admin Site/Manage users in django admin/project/library/models.py
from django.db import models
from django.urls import reverse
import uuid


class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f'{self.id} ({self.book.title})'

Admin Site/Manage users in django admin/project/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


class RegisterForm(UserCreationForm):
    password1 = forms.CharField(min_length=4, widget=forms.PasswordInput(attrs={
        'placeholder': 'Password'
    }), label='password')
    password2 = forms.CharField(min_length=4, widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password'
    }), label='Confirm Password')

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'password1']

    def clean_password2(self):
        password = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password and password2 and password != password2:
            raise forms.ValidationError("password and confirm password is not same")
        if len(password) < 4:
            raise forms.ValidationError('Password is very weak please enter 4 words at least')
        return password

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.staff = True
            user.set_password(self.cleaned_data['password1'])
            user.save()
        return user

Admin Site/Manage users in django admin/project/accounts/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from .models import User, UserProfile
from django.core.exceptions import PermissionDenied


def home(request):
    return render(request, 'accounts/index.html')


# Register
def register(request):
    form = RegisterForm
    if request.method == 'POST':
        form = form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    return render(request, 'accounts/register.html', {'forms': form})


# Profile View
def profile(request, id=None):
    context = {}
    try:
        user = User.objects.get(id=id)
        user = UserProfile.objects.get(user__email=user)
        context['userprofile'] = user
    except User.DoesNotExist:
        error = 'This User Does Not Exist'
        return render(request, 'page404.html', {'error': error})
    return render(request, 'accounts/profile.html', context)


# Delete User
def delete_user(request, id=None):
    if 'delete_user' in request.POST and id is not None:
        User.objects.get(id=id).delete()
    return redirect('accounts:register')

Admin Site/Manage users in django admin/project/library/views.py
from django.shortcuts import render

# Create your views here.

Admin Site/Manage users in django admin/project/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block title %} index {% endblock %}

{% block body %}

{% endblock %}

Admin Site/Manage users in django admin/project/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %} Login page {% endblock %}

{% block body %}
    <!-- User is live -->
    {% if not request.user.is_authenticated %}
        <div class="entry-links">
            <div class="container">
            <!-- Login -->
            {% if messages %}
                <div class="alert">
                    <div class="container">
                        {% for message in messages %}
                            <div class="alert text-warning alert-warning">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
            <div class="login-text">
                <div class="container">
                    <h2>Login Page</h2>
                </div>
            </div>
            <div class="login-page">
                <div class="container">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Login" class="btn btn-primary">
                        <!-- Register -->
                        <a class="btn btn-warning" href="{% url 'accounts:register' %}">register</a>
                    </form>
                </div>
            </div>
            </div>
        </div>

        {% else %}
        <!-- Logout -->
        <div class="logout">
            <div class="container">
                <a href="{% url 'accounts:logout' %}">Logout!</a> |
                <a href="{% url 'accounts:profile' request.user.id %}">Profile</a>
            </div>
        </div>
    {% endif %}
{% endblock %}

Admin Site/Manage users in django admin/project/accounts/templates/accounts/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="container">
        <h2>You are logged out</h2>
    </div>
</body>
</html>

Admin Site/Manage users in django admin/project/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block title %} {{ request.user.get_full_name }} {% endblock %}
{% block body %}
    <!-- General auth -->
    {% if request.user.is_authenticated %}
{#        {% if not perms.accounts.view_user %}#}
            <div class="profile">
                <div class="container">
                    <ul>
                        <li>{{ userprofile.user.get_full_name }}</li>
                    </ul>
                    <a>
                        <form action="{% url 'accounts:delete_user' request.user.pk %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="delete_user" value="{{ request.user.id }}">
                            <input class="btn btn-danger" type="submit" value="Remove Account">
                        </form>
                    </a>
                </div>
            </div>
{#        {% endif %}#}
    {% endif %}
{% endblock %}

Admin Site/Manage users in django admin/project/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% block title %} Register {% endblock %}

{% block body %}
<div class="register">
    <div class="container">
        <h3>Register</h3>
        <form method="post">
            {% csrf_token %}
            {% for form in forms %}
                {% for error in form.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
                <label>{{ form.label }}</label>
                <p>{{ form }}</p>
            {% endfor %}
            <input type="submit" value="Register!" class="btn btn-success">
        </form>
    </div>
</div>
{% endblock %}

Admin Site/Manage users in django admin/project/accounts/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %} Base file {% endblock %}</title>
        {% load static %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- First Mobile Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'index/css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'index/css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'index/css/style.css' %}" />
    <script src="{% static 'index/js/html5shiv.min.js' %}"></script>
    <script src="{% static 'index/js/respond.min.js' %}"></script>
    </head>
    <body>

        <script src="{% static 'index/js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'index/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'index/js/custom.js' %}"></script>
    </body>
    {% block body %}
    {% endblock %}
</html>

Admin Site/Manage users in django admin/project/accounts/templates/page404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .error .center {
            text-align: center;
        }
        .error .cutter {
            content: "";
            border: 1px solid #000;
            width: 100%
        }
    </style>
</head>
<body>
    <div class="error">
        <h1 class="heading-error center">Error 404</h1>
        <div class="cutter"></div>
        <div class="center">{{ error }}</div>
    </div>
</body>
</html>