UserApp/More than three users/project/app1/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import redirect

app_name = 'app1'


class Login(LoginView):
    template_name = 'app1/login.html'

    def get_success_url(self):
        return reverse_lazy('app1:profile', args=[self.request.user.id])

    def form_invalid(self, form):
        response = super().form_invalid(form)
        messages.error(self.request, 'username or password are invalid. please try again.', extra_tags='validate_form')
        return redirect('app1:login')


urlpatterns = [
    path('', Login.as_view(), name='login'),
    path('register/', views.register, name='register'),
    path('logout/', LogoutView.as_view(template_name='app1/logout.html', next_page=reverse_lazy('app1:login')), name='logout'),
    path('profile/<int:id>/', views.profile, name='profile'),
    path('delete/<int:id>/', views.delete_user, name='delete_user'),
]

UserApp/More than three users/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
]

UserApp/More than three users/project/app1/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager
from django.db.models.signals import post_save


class Role(models.Model):
    MEMBER      = 'Member'
    SECRETARY   = 'Secretary'
    SUPERVISOR  = 'Supervisor'
    ADMIN       = 'Admin'

    ROLE_CHOICES = (
        (MEMBER, 'Member'),
        (SECRETARY, 'Secretary'),
        (SUPERVISOR, 'Supervisor'),
        (ADMIN, 'Admin'),
    )

    id = models.CharField(max_length=20, choices=ROLE_CHOICES, primary_key=True)

    def __str__(self):
        return self.get_id_display()


class User(AbstractBaseUser, PermissionsMixin):
    roles = models.ManyToManyField(Role, blank=True)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    date_joined = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    admin = models.BooleanField(default=False)
    staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    def get_full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def get_short_name(self):
        return self.email

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_active(self):
        return self.active

    def has_perm(self, perm, obj=None):
        return True


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    overview = models.TextField(max_length=2000, blank=True)


def create_profile(sender, **kwargs):
    if kwargs['created']:
        Profile.objects.create(user=kwargs['instance'])


post_save.connect(receiver=create_profile, sender=User)

UserApp/More than three users/project/app1/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, Profile, Role


class RegisterForm(UserCreationForm):
    password1 = forms.CharField(min_length=4, widget=forms.PasswordInput(attrs={
        'placeholder': 'Password'
    }), label='password')
    password2 = forms.CharField(min_length=4, widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password'
    }), label='Confirm Password')

    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'roles', 'password1']
        widgets = {
            'roles': forms.CheckboxSelectMultiple()
        }

    def clean_password2(self):
        password = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password and password2 and password != password2:
            raise forms.ValidationError("password and confirm password is not same")
        if len(password) < 4:
            raise forms.ValidationError('Password is very weak please enter 4 words at least')
        return password

    def save(self, commit=True):
        user = super().save(commit=False)
        if commit:
            user.staff = True
            user.set_password(self.cleaned_data['password1'])
            user.save()
            user.roles.add(*self.cleaned_data['roles'])
        return user

UserApp/More than three users/project/app1/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from .models import User, Profile


def home(request):
    return render(request, 'app1/index.html')


# Register
def register(request):
    form = RegisterForm
    if request.method == 'POST':
        form = form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('app1:login')
    return render(request, 'app1/register.html', {'forms': form})


# Profile View
def profile(request, id=None):
    context = {}
    try:
        user = User.objects.get(id=id)
        user = Profile.objects.get(user__email=user)
        context['userprofile'] = user
    except User.DoesNotExist:
        error = 'This User Does Not Exist'
        return render(request, 'page404.html', {'error': error})
    return render(request, 'app1/profile.html', context)


# Delete User
def delete_user(request, id=None):
    if 'delete_user' in request.POST and id is not None:
        User.objects.get(id=id).delete()
    return redirect('app1:register')

UserApp/More than three users/project/app1/templates/app1/index.html
{% extends 'base.html' %}
{% block title %} index {% endblock %}

{% block body %}

{% endblock %}

UserApp/More than three users/project/app1/templates/app1/login.html
{% extends 'base.html' %}
{% block title %} Login page {% endblock %}

{% block body %}
    <!-- User is live -->
    {% if not request.user.is_authenticated %}
        <div class="entry-links">
            <div class="container">
            <!-- Login -->
            {% if messages %}
                <div class="alert">
                    <div class="container">
                        {% for message in messages %}
                            <div class="alert text-warning alert-warning">
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endif %}
            <div class="login-text">
                <div class="container">
                    <h2>Login Page</h2>
                </div>
            </div>
            <div class="login-page">
                <div class="container">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Login" class="btn btn-primary">
                        <!-- Register -->
                        <a class="btn btn-warning" href="{% url 'app1:register' %}">register</a>
                    </form>
                </div>
            </div>
            </div>
        </div>

        {% else %}
        <!-- Logout -->
        <div class="logout">
            <div class="container">
                <a href="{% url 'app1:logout' %}">Logout!</a>
            </div>
        </div>
    {% endif %}
{% endblock %}

UserApp/More than three users/project/app1/templates/app1/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div class="container">
        <h2>You are logged out</h2>
    </div>
</body>
</html>

UserApp/More than three users/project/app1/templates/app1/profile.html
{% extends 'base.html' %}
{% block title %} {{ request.user.get_full_name }} {% endblock %}
{% block body %}
    <!-- General auth -->
    {% if request.user.is_authenticated %}
        <div class="profile">
            <div class="container">
                <ul>
                    <li>{{ userprofile.user.get_full_name }}</li>
                </ul>
                <h2>Roles:</h2>
                {% for roles in userprofile.user.roles.all %}
                    <li>{{ roles }}</li>
                {% endfor %}
            </div>
        </div>
<a>
    <form action="{% url 'app1:delete_user' request.user.pk %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="delete_user" value="{{ request.user.id }}">
        <input class="btn btn-danger" type="submit" value="Remove Account">
    </form>
</a>
    {% endif %}
{% endblock %}

UserApp/More than three users/project/app1/templates/app1/register.html
{% extends 'base.html' %}
{% block title %} Register {% endblock %}

{% block body %}
<div class="register">
    <div class="container">
        <h3>Register</h3>
        <form method="post">
            {% csrf_token %}
            {% for form in forms %}
                {% for error in form.errors %}
                    <span class="text-danger">{{ error }}</span>
                {% endfor %}
                <label>{{ form.label }}</label>
                <p>{{ form }}</p>
            {% endfor %}
            <input type="submit" value="Register!" class="btn btn-success">
        </form>
    </div>
</div>
{% endblock %}

UserApp/More than three users/project/app1/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %} Base file {% endblock %}</title>
        {% load static %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- First Mobile Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'index/css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'index/css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'index/css/style.css' %}" />
    <script src="{% static 'index/js/html5shiv.min.js' %}"></script>
    <script src="{% static 'index/js/respond.min.js' %}"></script>
    </head>
    <body>

        <script src="{% static 'index/js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'index/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'index/js/custom.js' %}"></script>
    </body>
    {% block body %}
    {% endblock %}
</html>

UserApp/More than three users/project/app1/templates/page404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .error .center {
            text-align: center;
        }
        .error .cutter {
            content: "";
            border: 1px solid #000;
            width: 100%
        }
    </style>
</head>
<body>
    <div class="error">
        <h1 class="heading-error center">Error 404</h1>
        <div class="cutter"></div>
        <div class="center">{{ error }}</div>
    </div>
</body>
</html>